import Image from "next/image";
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function Home() {
  
 
  return (
    <><h1>h1</h1></>
  );
}