import Image from "next/image";
import { Metadata } from 'next';
import Container from '../ui/Container/Container';
import Htag from '../ui/Htag/Htag';
import Button from '../ui/Button/Button';
import Tag from '../ui/Tag/Tag';
import ArrowRight from '../ui/IconArrow/ArrowRight';
import Rating from '../components/rating/Rating'
import { useState } from 'react';
import ProductCard from '../components/product-card/ProdutCard';
import ProductPage from '../components/product-page/ProductPage';
import CartModal from '../components/cart-modal/CartModal';
import CartPage from '../components/cart-page/CartPage';
import Banner from '../components/banner/Banner';
import CheckoutPage from '../components/checkout-page/CheckoutPage';

export const metadata: Metadata = {
	title: "Test page",
	description: "Generated by create next app",
};


export default function Test() {


	return (

		<div className="flex min-h-full flex-1 flex-col justify-center px-6 py-12 lg:px-8">
			<ProductCard />
			<CartModal />
			<CartPage />
			<Banner />
			<ProductPage />
			<CheckoutPage />
			
			<Container fluid>
				<div className="sm:mx-auto sm:w-full sm:max-w-sm">
					<Htag tag={'h2'} className="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Sign in to your account</Htag>
					<Rating />
				</div>

			</Container>

			<div className="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
				<form className="space-y-6" action="#" method="POST">
					<div>
						<label htmlFor="email" className="block text-sm font-medium leading-6 text-gray-900">
							Email address
						</label>
						<div className="mt-2">
							<input
								id="email"
								name="email"
								type="email"
								autoComplete="email"
								required
								className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
							/>
						</div>
					</div>

					<div>
						<div className="flex items-center justify-between">
							<label htmlFor="password" className="block text-sm font-medium leading-6 text-gray-900">
								Password
							</label>
							<div className="text-sm">
								<a href="#" className="font-semibold text-indigo-600 hover:text-indigo-500">
									Forgot password?
								</a>
							</div>
						</div>
						<div className="mt-2">
							<input
								id="password"
								name="password"
								type="password"
								autoComplete="current-password"
								required
								className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
							/>
						</div>
					</div>

					<div>
						<button
							type="submit"
							className="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
						>
							Sign in
						</button>
						<Button className='btn btn-primary' appearence='dark'>
							Test button
							<ArrowRight
								alt="Vercel Logo"
								className="icon"
								width={20}
								height={20}
								fill="#fff"

							/>
						</Button>
						<Button className='btn btn-primary' appearence='primary'>
							Test button
							<ArrowRight
								alt="Vercel Logo"
								className="icon"
								width={20}
								height={20}
								fill="#fff"

							/>
						</Button>
						<Button className='btn btn-primary' appearence='light'>Test button</Button>
						<Tag size='sm' >Category</Tag>
						<Tag size='md' >Category</Tag>
						<Tag size='lg' >Category</Tag>
					</div>
				</form>

				<p className="mt-10 text-center text-sm text-gray-500">
					Not a member?{' '}
					<a href="#" className="font-semibold leading-6 text-indigo-600 hover:text-indigo-500">
						Start a 14 day free trial
					</a>
				</p>
			</div>
		</div>

	);
}
